To mask row, use the mask times the matrix
To mask column, use right multiplication

trip: 1. to make a diagnol matrix, the input should be a vector (that is the rank is one)
      2. to use tf.matmul, the two operands should be of the same type.

In [23]:
import tensorflow as tf
t1 = tf.ones([3,4])
print "dtype of t1: ", t1
t1 = tf.cast(t1,tf.int32)

row_mask = tf.pack([1,0,1])
print row_mask.get_shape()

dtype of t1:  Tensor("ones_6:0", shape=(3, 4), dtype=float32)
(3,)


In [24]:
t_row = tf.matmul(tf.diag(row_mask), t1)

In [15]:
sess = tf.Session()

t1_v, t_row_v = sess.run([t1,t_row])

In [17]:
print t1_v
print t_row_v

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]]
