In [ ]:
#1 matrix multiplication

tf.dynamic_partition
tf.matmul(,,transpose_a=True)
*  tf.multiply
tf.ones([n,m])
tf.transpose()
create a mask. object detection
convolution operation. 

In [5]:
import tensorflow as tf
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3]) 

b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2]) 
c = tf.matmul(a, b)


In [6]:
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(c))

[[1 2 3]
 [4 5 6]]
[[ 58  64]
 [139 154]]
