In [1]:
# what saver save in each checkpoint: three files (.data, .index, .meta) and a file named "checkpoint" is saved

# when resume a trainer, you need to create recreate the variables 

In [1]:
import tensorflow as tf
import numpy as np
import os


x = tf.placeholder(tf.float32, [16, 3],name = "input")  # input
y = tf.placeholder(tf.float32, [16, 1],name = "output")   # output

w = tf.Variable(tf.zeros([3, 1]), dtype=tf.float32,name ="weight")
global_step = tf.Variable(0,trainable = False,name="global_step")
#global_step = tf.Variable(0, trainable=False)

res = tf.matmul(x, w,name="multiplication_op")
loss = tf.reduce_sum(tf.square(res - y),name="loss")

train_op = tf.train.GradientDescentOptimizer(0.01).minimize(loss,global_step = global_step,name= "train_op")

In [2]:
saver = tf.train.Saver(max_to_keep=2, keep_checkpoint_every_n_hours=1)

In [3]:
print [v.name for v in tf.global_variables()]

[u'weight:0', u'global_step:0']


In [4]:
# Start a session
max_steps = 2
with tf.Session() as sess:
    # initialize the variables
    sess.run(tf.global_variables_initializer())

    for step in range(max_steps):
        feed_dict = {x: np.random.randn(16, 3), y: np.random.randn(16, 1)}  # dummy input
        _, loss_value = sess.run([train_op, loss], feed_dict=feed_dict)

        
        saver.save(sess, "./model/", global_step=global_step)
        print global_step.eval()
        print w.eval()

1
[[ 0.04161121]
 [ 0.02138496]
 [-0.04474959]]
2
[[ 0.01409703]
 [ 0.0305276 ]
 [-0.17594406]]


In [5]:
graph = tf.get_default_graph()
output_dir = './model'
ckpt = tf.train.get_checkpoint_state(output_dir)

sess2 = tf.InteractiveSession()
saver = tf.train.import_meta_graph(ckpt.model_checkpoint_path+'.meta')
saver.restore(sess2,ckpt.model_checkpoint_path)


In [9]:
for t in [n.name for n in tf.get_default_graph().as_graph_def().node]:
    if "loss "

[u'input',
 u'output',
 u'zeros',
 u'weight',
 u'weight/Assign',
 u'weight/read',
 u'global_step/initial_value',
 u'global_step',
 u'global_step/Assign',
 u'global_step/read',
 u'multiplication_op',
 u'sub',
 u'Square',
 u'Const',
 u'loss',
 u'gradients/Shape',
 u'gradients/Const',
 u'gradients/Fill',
 u'gradients/loss_grad/Reshape/shape',
 u'gradients/loss_grad/Reshape',
 u'gradients/loss_grad/Tile/multiples',
 u'gradients/loss_grad/Tile',
 u'gradients/Square_grad/mul/x',
 u'gradients/Square_grad/mul',
 u'gradients/Square_grad/mul_1',
 u'gradients/sub_grad/Shape',
 u'gradients/sub_grad/Shape_1',
 u'gradients/sub_grad/BroadcastGradientArgs',
 u'gradients/sub_grad/Sum',
 u'gradients/sub_grad/Reshape',
 u'gradients/sub_grad/Sum_1',
 u'gradients/sub_grad/Neg',
 u'gradients/sub_grad/Reshape_1',
 u'gradients/sub_grad/tuple/group_deps',
 u'gradients/sub_grad/tuple/control_dependency',
 u'gradients/sub_grad/tuple/control_dependency_1',
 u'gradients/multiplication_op_grad/MatMul',
 u'gradients

In [6]:
w_r = graph.get_tensor_by_name("weight:0")

In [7]:
print w_r.eval()

[[-0.07830708]
 [ 0.09175968]
 [ 0.13301343]]
