In [ ]:
no need to use a placehoder and pass the numpy to the graph

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
A = np.array([[1,2,3],[3,4,5]])
B = np.array([[5,6],[7,8]])

C = tf.concat(1, (A,B))

D = tf.slice(A,[0,0],[-1,1])

sess = tf.Session()

print C.get_shape().as_list()
print sess.run(C)
print sess.run(D)

[2, 5]
[[1 2 3 5 6]
 [3 4 5 7 8]]
[[1]
 [3]]
