In [69]:
# This loss is for a location task. So two coordiates and classification label are 
# predicted. If there is no object, the loss for regression task is zeros

In [70]:
import tensorflow as tf
import keras
import numpy as np
from keras import backend as K

In [71]:
#create a pred and a truth. Suppose 4 regression task and 4 corresponding classification
# task
batch_size = 2
p = 4
pred1 = np.random.random((batch_size,p))
pred2 = np.random.randint(2,size=(batch_size,p))
pred = np.concatenate((pred1,pred2), axis = 1)

truth1 = np.random.random((batch_size,p))
truth2 = np.random.randint(2,size=(batch_size,p))
truth = np.concatenate((truth1,truth2), axis = 1)

In [72]:
def myloss(pred,truth):
    pred_w = tf.slice(truth,[0,0],[batch_size,p])*tf.slice(truth,[0,p],[batch_size,p])
    truth_w = tf.slice(pred,[0,0],[batch_size,p])*tf.slice(truth,[0,p],[batch_size,p])
    losses =tf.losses.mean_squared_error(pred_w,truth_w)
    return losses

In [73]:
pred_holder = tf.placeholder(tf.float32,[batch_size,2*p])
true_holder = tf.placeholder(tf.float32,[batch_size,2*p])
loss = myloss(pred_holder,true_holder)

In [74]:
with tf.Session() as sess:
    res = sess.run(loss,feed_dict =  {pred_holder: pred, true_holder:truth})
    print(res)

0.118732


In [68]:
truth[:,4:]

array([[ 0.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.]])

In [46]:
truth

array([[ 0.125517  ,  0.84539533,  0.39157235,  0.24540973,  0.        ,
         0.        ,  1.        ,  1.        ],
       [ 0.33080374,  0.56422006,  0.96803472,  0.23929137,  1.        ,
         0.        ,  1.        ,  1.        ]])

In [47]:
pred

array([[ 0.2931445 ,  0.3802023 ,  0.70936867,  0.65773757,  1.        ,
         0.        ,  1.        ,  0.        ],
       [ 0.18161072,  0.9817209 ,  0.06135219,  0.93188056,  0.        ,
         1.        ,  1.        ,  0.        ]])