In [ ]:
The gateway (placeholder) for should be defined again.
tf 0.12.1 version

In [10]:
import tensorflow as tf
import numpy as np
state_size = 10
input_len =5
batch_size=3
input = np.full((batch_size,input_len), 1.2)


In [19]:
class Agent:
    def __init__(self):
        self.rnn_cell = None
        self.initialized = False
        self.batch_size = None
        self.output = None
        self.rnn_state_t=None
    def first(self,input_t):
        self.batch_size = tf.unpack(tf.shape(input_t))[0]
        with tf.variable_scope("rnn"):
            self.rnn_cell = tf.nn.rnn_cell.BasicLSTMCell(state_size)
            self.rnn_state_t = self.rnn_cell.zero_state(self.batch_size,tf.float32)
        output_= self.predict(input_t)
        self.initialized = True
        return output_
    def predict(self,input_t):

        if self.initialized:
            tf.get_variable_scope().reuse_variables()
        with tf.variable_scope("rnn/RNN",reuse=True):
            output_, self.rnn_state_t = self.rnn_cell(input_t, self.rnn_state_t)

            self.output = output_
            
            zero_state = self.rnn_cell.zero_state(self.batch_size,tf.float32)
            
            tf.get_variable_scope().reuse_variables()
            output_zero_state, self.rnn_state_t = \
                       self.rnn_cell(input_t, zero_state)
        return output_ , output_zero_state

In [20]:
input_t = tf.placeholder(tf.float32,(None,input_len))
# Define a testing agent

agent2 = Agent()
output3_t = agent2.first(input_t)

saver = tf.train.Saver()
sess = tf.Session()
saver.restore(sess, './checkpoints/model.ckpt')


In [26]:
output3_v = sess.run(output3_t,{input_t: input})

In [27]:
output3_v

(array([[ 0.05176976, -0.09401996,  0.11417688, -0.10251397, -0.04254346,
          0.14024873,  0.22409359,  0.10744734, -0.19361506,  0.4428536 ],
        [ 0.05176976, -0.09401996,  0.11417688, -0.10251397, -0.04254346,
          0.14024873,  0.22409359,  0.10744734, -0.19361506,  0.4428536 ],
        [ 0.05176976, -0.09401996,  0.11417688, -0.10251397, -0.04254346,
          0.14024873,  0.22409359,  0.10744734, -0.19361506,  0.4428536 ]], dtype=float32),
 array([[ 0.05176976, -0.09401996,  0.11417688, -0.10251397, -0.04254346,
          0.14024873,  0.22409359,  0.10744734, -0.19361506,  0.4428536 ],
        [ 0.05176976, -0.09401996,  0.11417688, -0.10251397, -0.04254346,
          0.14024873,  0.22409359,  0.10744734, -0.19361506,  0.4428536 ],
        [ 0.05176976, -0.09401996,  0.11417688, -0.10251397, -0.04254346,
          0.14024873,  0.22409359,  0.10744734, -0.19361506,  0.4428536 ]], dtype=float32))

In [24]:
output3_v

(array([[ 0.05176976, -0.09401996,  0.11417688, -0.10251397, -0.04254346,
          0.14024873,  0.22409359,  0.10744734, -0.19361506,  0.4428536 ],
        [ 0.05176976, -0.09401996,  0.11417688, -0.10251397, -0.04254346,
          0.14024873,  0.22409359,  0.10744734, -0.19361506,  0.4428536 ],
        [ 0.05176976, -0.09401996,  0.11417688, -0.10251397, -0.04254346,
          0.14024873,  0.22409359,  0.10744734, -0.19361506,  0.4428536 ]], dtype=float32),
 array([[ 0.05176976, -0.09401996,  0.11417688, -0.10251397, -0.04254346,
          0.14024873,  0.22409359,  0.10744734, -0.19361506,  0.4428536 ],
        [ 0.05176976, -0.09401996,  0.11417688, -0.10251397, -0.04254346,
          0.14024873,  0.22409359,  0.10744734, -0.19361506,  0.4428536 ],
        [ 0.05176976, -0.09401996,  0.11417688, -0.10251397, -0.04254346,
          0.14024873,  0.22409359,  0.10744734, -0.19361506,  0.4428536 ]], dtype=float32))