tf.gather() # use a index tensor to select
tf.slice() 
tf.mask() # use a boolean tensor to select
indexing
unpack
tf.dynamic_partition
tf.split

In [9]:
import tensorflow as tf
logits = tf.constant([[[10.0, 10.0, 20.0, 20.0],
                      [11.0, 10.0, 10.0, 30.0],
                      [12.0, 10.0, 10.0, 20.0],
                      [13.0, 10.0, 10.0, 20.0]],
                     [[14.0, 11.0, 21.0, 31.0],
                      [15.0, 11.0, 11.0, 21.0],
                      [16.0, 11.0, 11.0, 21.0],
                      [17.0, 11.0, 11.0, 21.0]]])

indices = tf.constant([[[0, 0], [0, 1]], [[1, 1], [1, 3]]])
print logits.get_shape()
one_slice = logits[:,:,0:1]
print one_slice.get_shape()

result = tf.gather_nd(logits, indices)
with tf.Session() as sess:
    print(sess.run(result))

(2, 4, 4)
(2, 4, 1)
[[[ 10.  10.  20.  20.]
  [ 11.  10.  10.  30.]]

 [[ 15.  11.  11.  21.]
  [ 17.  11.  11.  21.]]]


# works on tf 0.12
logits = tf.constant([[[10.0, 10.0, 20.0, 20.0],
                      [11.0, 10.0, 10.0, 30.0],
                      [12.0, 10.0, 10.0, 20.0],
                      [13.0, 10.0, 10.0, 20.0]],
                     [[14.0, 11.0, 21.0, 31.0],
                      [15.0, 11.0, 11.0, 21.0],
                      [16.0, 11.0, 11.0, 21.0],
                      [17.0, 11.0, 11.0, 21.0]]])

split0, split1 = tf.split(logits,[1,3],2)
print(split1.get_shape())

In [15]:
?tf.unpack